mkdir ExtractPitchLines/datasets/soccer_seg_detection
mkdir ExtractPitchLines/datasets/soccer_seg_detection/test
mkdir ExtractPitchLines/datasets/soccer_seg_detection/train_phase_1
mkdir ExtractPitchLines/datasets/soccer_seg_detection/train_phase_2
mkdir ExtractPitchLines/datasets/soccer_seg_detection/val
